// Model factory: kind string → 3D model instance.
import { CAT_COLOR } from '../palette.js';
import {
  AuroraModel,
  BudgetsModel,
  CertModel,
  CloudFormationModel,
  CloudTrailModel,
  CloudWatchModel,
  EBSModel,
  ECRModel,
  EFSModel,
  EventBridgeModel,
  ExternalModel,
  GlobeModel,
  IAMModel,
  KinesisModel,
  KMSModel,
  NACLModel,
  OutlineModel,
  PersonModel,
  RegionModel,
  ResponsibilityModel,
  SQSModel,
  SSMModel,
  StepFunctionsModel,
  TileModel,
  TokenModel,
  UsersModel,
  VaultModel,
  ZoneModel,
} from './misc.js';
import {
  CloudFrontModel,
  DynamoDBModel,
  EC2Model,
  ECSModel,
  ELBModel,
  GateModel,
  LambdaModel,
  NATModel,
  RDSModel,
  Route53Model,
  S3Model,
} from './services.js';

const FACTORY = {
  ec2: (o) => new EC2Model(o),
  elb: (o) => new ELBModel(o),
  s3: (o) => new S3Model(o),
  rds: (o) => new RDSModel(o),
  dynamodb: (o) => new DynamoDBModel(o),
  lambda: (o) => new LambdaModel(o),
  ecs: (o) => new ECSModel(o),
  apigw: (o) => new GateModel(o),
  igw: (o) => new GateModel({ kind: 'igw', category: 'network', color: CAT_COLOR.network, dark: '#2e2366', ...o }),
  cloudfront: (o) => new CloudFrontModel(o),
  edge: (o) => {
    const m = new CloudFrontModel({ scale: 0.6, ...o });
    m.kind = 'edge';
    return m;
  },
  route53: (o) => new Route53Model(o),
  nat: (o) => new NATModel(o),
  external: (o) => new ExternalModel(o),
  users: (o) => new UsersModel(o),
  user: (o) => new PersonModel(o),
  az: (o) => new ZoneModel(o),
  zone: (o) => new ZoneModel({ kind: 'zone', ...o }),
  region: (o) => new RegionModel(o),
  outline: (o) => new OutlineModel(o),
  subnet: (o) => new TileModel(o),
  globe: (o) => new GlobeModel(o),
  token: (o) => new TokenModel(o),
  sns: (o) => new TokenModel({ shape: 'card', color: '#be185d', text: 'SNS', size: 1.2, ...o }),
  cache: (o) => new TokenModel({ kind: 'cache', category: 'database', color: CAT_COLOR.database, shape: 'disc', text: 'Cache', glow: true, size: 1.0, bob: 0.03, ...o }),
  waf: (o) => new TokenModel({ kind: 'waf', category: 'security', color: CAT_COLOR.security, shape: 'card', text: 'WAF', glow: true, size: 1.1, ...o }),
  shield: (o) => new TokenModel({ kind: 'shield', category: 'security', color: CAT_COLOR.security, shape: 'card', text: 'Shield', glow: true, size: 1.1, ...o }),
  secrets: (o) => new TokenModel({ kind: 'secrets', category: 'security', color: CAT_COLOR.security, shape: 'cube', text: 'Secrets', fontSize: 58, glow: true, size: 1.2, ...o }),
  cognito: (o) => new TokenModel({ kind: 'cognito', category: 'security', color: CAT_COLOR.security, shape: 'card', text: 'Cognito', fontSize: 56, glow: true, size: 1.5, ...o }),
  cloudwatch: (o) => new CloudWatchModel(o),
  sqs: (o) => new SQSModel(o),
  iam: (o) => new IAMModel(o),
  ebs: (o) => new EBSModel(o),
  snapshot: (o) => new TokenModel({ kind: 'snapshot', category: 'storage', color: '#3f6212', shape: 'disc', text: 'Snap', fontSize: 84, size: 0.9, ...o }),
  kms: (o) => new KMSModel(o),
  cloudtrail: (o) => new CloudTrailModel(o),
  eventbridge: (o) => new EventBridgeModel(o),
  cloudformation: (o) => new CloudFormationModel(o),
  budgets: (o) => new BudgetsModel(o),
  costexplorer: (o) => new CloudWatchModel({ kind: 'costexplorer', title: 'Chi phí $ / ngày', ...o }),
  acm: (o) => new CertModel(o),
  stepfunctions: (o) => new StepFunctionsModel(o),
  efs: (o) => new EFSModel(o),
  ecr: (o) => new ECRModel(o),
  aurora: (o) => new AuroraModel(o),
  resp: (o) => new ResponsibilityModel(o),
  mount: (o) => new TokenModel({ kind: 'mount', category: 'storage', color: '#3f6212', shape: 'disc', text: 'NFS', fontSize: 84, size: 0.8, ...o }),
  // VPC Endpoint: a small gate on the VPC edge (gateway type) or a network card in the subnet (interface type)
  vpce: (o) => new GateModel({ kind: 'vpce', category: 'network', color: '#a78bfa', dark: '#2e2366', scale: 0.75, ...o }),
  eni: (o) => new TokenModel({ kind: 'eni', category: 'network', color: CAT_COLOR.network, shape: 'card', text: 'ENI', glow: true, size: 1.0, ...o }),
  sg: (o) => new OutlineModel({ kind: 'sg', category: 'network', color: '#DD344C', ...o }),
  nacl: (o) => new NACLModel(o),
  // AWS Organizations: management account, member accounts, OUs and SCP cards
  org: (o) => new TokenModel({ kind: 'org', category: 'management', color: '#1e3a8a', shape: 'cube', text: 'Mgmt', fontSize: 76, glow: true, size: 1.4, ...o }),
  account: (o) => new TokenModel({ kind: 'account', category: 'management', color: '#2563eb', shape: 'cube', fontSize: 70, size: 1.25, ...o }),
  ou: (o) => new ZoneModel({ kind: 'ou', category: 'management', color: CAT_COLOR.management, top: '#e0e7ff', side: '#a5b4fc', ...o }),
  scp: (o) => new TokenModel({ kind: 'scp', category: 'management', color: '#b45309', shape: 'card', text: 'SCP', glow: true, size: 1.1, ...o }),
  kinesis: (o) => new KinesisModel(o),
  firehose: (o) => new TokenModel({ kind: 'firehose', category: 'integration', color: '#7c3aed', shape: 'card', text: 'Firehose', fontSize: 50, glow: true, size: 1.4, ...o }),
  ssm: (o) => new SSMModel(o),
  backup: (o) => new VaultModel(o),
  // security & governance: IAM Identity Center, GuardDuty, AWS Config, Trusted Advisor
  idc: (o) => new TokenModel({ kind: 'idc', category: 'security', color: CAT_COLOR.security, shape: 'cube', text: 'SSO', fontSize: 80, glow: true, size: 1.4, ...o }),
  permset: (o) => new TokenModel({ kind: 'permset', category: 'security', color: '#9f1239', shape: 'card', text: 'PermSet', fontSize: 52, glow: true, size: 1.2, ...o }),
  guardduty: (o) => new TokenModel({ kind: 'guardduty', category: 'security', color: CAT_COLOR.security, shape: 'cube', text: 'GuardDuty', fontSize: 44, glow: true, size: 1.5, ...o }),
  finding: (o) => new TokenModel({ kind: 'finding', category: 'security', color: '#b91c1c', shape: 'card', text: 'Finding', fontSize: 56, glow: true, size: 1.1, ...o }),
  config: (o) => new TokenModel({ kind: 'config', category: 'management', color: CAT_COLOR.management, shape: 'cube', text: 'Config', fontSize: 64, glow: true, size: 1.4, ...o }),
  rule: (o) => new TokenModel({ kind: 'rule', category: 'management', color: '#1d4ed8', shape: 'card', text: 'Rule', fontSize: 72, glow: true, size: 1.0, ...o }),
  advisor: (o) => new TokenModel({ kind: 'advisor', category: 'management', color: '#1e40af', shape: 'cube', text: 'Advisor', fontSize: 56, glow: true, size: 1.4, ...o }),
  miner: (o) => new TokenModel({ kind: 'miner', category: 'compute', color: '#7f1d1d', shape: 'cube', text: 'Miner', fontSize: 62, glow: true, size: 1.0, ...o }),
  param: (o) => new TokenModel({ kind: 'param', category: 'management', color: '#1d4ed8', shape: 'card', text: 'Param', fontSize: 66, glow: true, size: 1.2, ...o }),
  // containers & PaaS: the EKS control plane, Kubernetes pods, Elastic Beanstalk
  eks: (o) => new TokenModel({ kind: 'eks', category: 'compute', color: CAT_COLOR.compute, shape: 'cube', text: 'EKS', fontSize: 84, glow: true, size: 1.4, ...o }),
  pod: (o) => new TokenModel({ kind: 'pod', category: 'compute', color: '#c2410c', shape: 'cube', text: 'Pod', fontSize: 70, glow: true, size: 0.75, ...o }),
  beanstalk: (o) => new TokenModel({ kind: 'beanstalk', category: 'compute', color: '#b45309', shape: 'cube', text: 'Beanstalk', fontSize: 40, glow: true, size: 1.4, ...o }),
  // developer tools: the CI/CD pipeline and its build / deploy stages, X-Ray tracing
  codepipeline: (o) => new TokenModel({ kind: 'codepipeline', category: 'devtools', color: CAT_COLOR.devtools, shape: 'cube', text: 'Pipeline', fontSize: 46, glow: true, size: 1.4, ...o }),
  codebuild: (o) => new TokenModel({ kind: 'codebuild', category: 'devtools', color: '#0f766e', shape: 'cube', text: 'Build', fontSize: 62, glow: true, size: 1.2, ...o }),
  codedeploy: (o) => new TokenModel({ kind: 'codedeploy', category: 'devtools', color: '#115e59', shape: 'cube', text: 'Deploy', fontSize: 54, glow: true, size: 1.2, ...o }),
  xray: (o) => new TokenModel({ kind: 'xray', category: 'devtools', color: CAT_COLOR.devtools, shape: 'cube', text: 'X-Ray', fontSize: 62, glow: true, size: 1.4, ...o }),
};

export function createModel(kind, opts = {}) {
  const make = FACTORY[kind];
  if (!make) throw new Error(`unknown model kind: ${kind}`);
  return make(opts);
}

export const MODEL_KINDS = Object.keys(FACTORY);
